server:
  tomcat:
    max-threads: 300
    accept-count: 100

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/sourceDb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    hikari:
      maximum-pool-size: 50  # Increase this to 50 or more based on your system's capabilities.
      minimum-idle: 50  # Keep a minimum number of idle connections for faster reuse.
      idle-timeout: 30000  # Optional: Set timeout for idle connections (in milliseconds).
      connection-timeout: 30000  # Optional: Set timeout for acquiring a connection (in milliseconds).
      max-lifetime: 600000  # Optional: Set max lifetime for connections.
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        generate_statistics: true
        show_sql: true
  
  cache:
    cache-names: fallbackClosures
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=60s,recordStats
logging:
  level:
    org:
      hibernate:
        stat: DEBUG
splunk:
  url: http://host.docker.internal:8088
