server:
  tomcat:
    max-threads: 300
    accept-count: 100

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/sourceDb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
  cache:
    cache-names: fallbackClosures
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=60s,recordStats