server:
  tomcat:
    max-threads: 300
    accept-count: 100

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:8666/sourceDb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        generate_statistics: true
        show_sql: true
    hikari:
      maximum-pool-size: 20
      minimum-idle: 20
      idle-timeout: 600000
      max-lifetime: 1800000
  cache:
    cache-names: fallbackClosures
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=60s,recordStats
logging:
  level:
    org:
      hibernate:
        stat: DEBUG
